# Generated by Django 4.1.9 on 2023-06-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('PostContent', models.TextField()),
            ],
        ),
    ]
